# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Staff/uqyche38/fine-settling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Staff/uqyche38/fine-settling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Staff/uqyche38/fine-settling/CMakeFiles /home/Staff/uqyche38/fine-settling/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Staff/uqyche38/fine-settling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_fine_settling

# Build rule for target.
test_fine_settling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fine_settling
.PHONY : test_fine_settling

# fast build rule for target.
test_fine_settling/fast:
	$(MAKE) -f CMakeFiles/test_fine_settling.dir/build.make CMakeFiles/test_fine_settling.dir/build
.PHONY : test_fine_settling/fast

#=============================================================================
# Target rules for targets named test_fine_settling1

# Build rule for target.
test_fine_settling1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fine_settling1
.PHONY : test_fine_settling1

# fast build rule for target.
test_fine_settling1/fast:
	$(MAKE) -f CMakeFiles/test_fine_settling1.dir/build.make CMakeFiles/test_fine_settling1.dir/build
.PHONY : test_fine_settling1/fast

#=============================================================================
# Target rules for targets named test_fine_settling_clean

# Build rule for target.
test_fine_settling_clean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fine_settling_clean
.PHONY : test_fine_settling_clean

# fast build rule for target.
test_fine_settling_clean/fast:
	$(MAKE) -f CMakeFiles/test_fine_settling_clean.dir/build.make CMakeFiles/test_fine_settling_clean.dir/build
.PHONY : test_fine_settling_clean/fast

#=============================================================================
# Target rules for targets named test_fine_settling_clean1

# Build rule for target.
test_fine_settling_clean1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fine_settling_clean1
.PHONY : test_fine_settling_clean1

# fast build rule for target.
test_fine_settling_clean1/fast:
	$(MAKE) -f CMakeFiles/test_fine_settling_clean1.dir/build.make CMakeFiles/test_fine_settling_clean1.dir/build
.PHONY : test_fine_settling_clean1/fast

test_fine_settling.o: test_fine_settling.cpp.o
.PHONY : test_fine_settling.o

# target to build an object file
test_fine_settling.cpp.o:
	$(MAKE) -f CMakeFiles/test_fine_settling.dir/build.make CMakeFiles/test_fine_settling.dir/test_fine_settling.cpp.o
.PHONY : test_fine_settling.cpp.o

test_fine_settling.i: test_fine_settling.cpp.i
.PHONY : test_fine_settling.i

# target to preprocess a source file
test_fine_settling.cpp.i:
	$(MAKE) -f CMakeFiles/test_fine_settling.dir/build.make CMakeFiles/test_fine_settling.dir/test_fine_settling.cpp.i
.PHONY : test_fine_settling.cpp.i

test_fine_settling.s: test_fine_settling.cpp.s
.PHONY : test_fine_settling.s

# target to generate assembly for a file
test_fine_settling.cpp.s:
	$(MAKE) -f CMakeFiles/test_fine_settling.dir/build.make CMakeFiles/test_fine_settling.dir/test_fine_settling.cpp.s
.PHONY : test_fine_settling.cpp.s

test_fine_settling1.o: test_fine_settling1.cpp.o
.PHONY : test_fine_settling1.o

# target to build an object file
test_fine_settling1.cpp.o:
	$(MAKE) -f CMakeFiles/test_fine_settling1.dir/build.make CMakeFiles/test_fine_settling1.dir/test_fine_settling1.cpp.o
.PHONY : test_fine_settling1.cpp.o

test_fine_settling1.i: test_fine_settling1.cpp.i
.PHONY : test_fine_settling1.i

# target to preprocess a source file
test_fine_settling1.cpp.i:
	$(MAKE) -f CMakeFiles/test_fine_settling1.dir/build.make CMakeFiles/test_fine_settling1.dir/test_fine_settling1.cpp.i
.PHONY : test_fine_settling1.cpp.i

test_fine_settling1.s: test_fine_settling1.cpp.s
.PHONY : test_fine_settling1.s

# target to generate assembly for a file
test_fine_settling1.cpp.s:
	$(MAKE) -f CMakeFiles/test_fine_settling1.dir/build.make CMakeFiles/test_fine_settling1.dir/test_fine_settling1.cpp.s
.PHONY : test_fine_settling1.cpp.s

test_fine_settling_clean.o: test_fine_settling_clean.cpp.o
.PHONY : test_fine_settling_clean.o

# target to build an object file
test_fine_settling_clean.cpp.o:
	$(MAKE) -f CMakeFiles/test_fine_settling_clean.dir/build.make CMakeFiles/test_fine_settling_clean.dir/test_fine_settling_clean.cpp.o
.PHONY : test_fine_settling_clean.cpp.o

test_fine_settling_clean.i: test_fine_settling_clean.cpp.i
.PHONY : test_fine_settling_clean.i

# target to preprocess a source file
test_fine_settling_clean.cpp.i:
	$(MAKE) -f CMakeFiles/test_fine_settling_clean.dir/build.make CMakeFiles/test_fine_settling_clean.dir/test_fine_settling_clean.cpp.i
.PHONY : test_fine_settling_clean.cpp.i

test_fine_settling_clean.s: test_fine_settling_clean.cpp.s
.PHONY : test_fine_settling_clean.s

# target to generate assembly for a file
test_fine_settling_clean.cpp.s:
	$(MAKE) -f CMakeFiles/test_fine_settling_clean.dir/build.make CMakeFiles/test_fine_settling_clean.dir/test_fine_settling_clean.cpp.s
.PHONY : test_fine_settling_clean.cpp.s

test_fine_settling_clean1.o: test_fine_settling_clean1.cpp.o
.PHONY : test_fine_settling_clean1.o

# target to build an object file
test_fine_settling_clean1.cpp.o:
	$(MAKE) -f CMakeFiles/test_fine_settling_clean1.dir/build.make CMakeFiles/test_fine_settling_clean1.dir/test_fine_settling_clean1.cpp.o
.PHONY : test_fine_settling_clean1.cpp.o

test_fine_settling_clean1.i: test_fine_settling_clean1.cpp.i
.PHONY : test_fine_settling_clean1.i

# target to preprocess a source file
test_fine_settling_clean1.cpp.i:
	$(MAKE) -f CMakeFiles/test_fine_settling_clean1.dir/build.make CMakeFiles/test_fine_settling_clean1.dir/test_fine_settling_clean1.cpp.i
.PHONY : test_fine_settling_clean1.cpp.i

test_fine_settling_clean1.s: test_fine_settling_clean1.cpp.s
.PHONY : test_fine_settling_clean1.s

# target to generate assembly for a file
test_fine_settling_clean1.cpp.s:
	$(MAKE) -f CMakeFiles/test_fine_settling_clean1.dir/build.make CMakeFiles/test_fine_settling_clean1.dir/test_fine_settling_clean1.cpp.s
.PHONY : test_fine_settling_clean1.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test_fine_settling_clean"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_fine_settling1"
	@echo "... test_fine_settling_clean1"
	@echo "... test_fine_settling"
	@echo "... test_fine_settling.o"
	@echo "... test_fine_settling.i"
	@echo "... test_fine_settling.s"
	@echo "... test_fine_settling1.o"
	@echo "... test_fine_settling1.i"
	@echo "... test_fine_settling1.s"
	@echo "... test_fine_settling_clean.o"
	@echo "... test_fine_settling_clean.i"
	@echo "... test_fine_settling_clean.s"
	@echo "... test_fine_settling_clean1.o"
	@echo "... test_fine_settling_clean1.i"
	@echo "... test_fine_settling_clean1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

